# Generated by Django 4.2.4 on 2023-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinopluyuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(choices=[('İstanbul', 'Istanbul'), ('Sinop', 'Sinop'), ('Ankara', 'Ankara')], max_length=20)),
                ('first_name', models.CharField(max_length=20, verbose_name='adı')),
                ('last_name', models.CharField(max_length=20, verbose_name='soyadı')),
                ('number', models.IntegerField(verbose_name='Telefon no')),
                ('content', models.TextField(verbose_name='içerik')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='kayıt tarihi')),
                ('is_active', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sinoplular',
                'ordering': ['publishing_date'],
            },
        ),
    ]
