# Generated by Django 4.2.4 on 2023-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0002_alter_sinopluyuz_options_alter_sinopluyuz_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinopluyuz',
            options={'ordering': ['publishing_date'], 'verbose_name_plural': 'Sinoplular_Listesi'},
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='sehir',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], default='istanbul', max_length=20, verbose_name='Şehir'),
        ),
    ]
