# Generated by Django 4.2.4 on 2023-10-03 10:38

from django.db import migrations, models
import sinoplu.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0003_alter_sinopluyuz_options_alter_sinopluyuz_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinopluyuz',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=sinoplu.models.user_directory_path),
        ),
    ]
