# Generated by Django 4.2.4 on 2023-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0006_alter_sinopluyuz_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinopluyuz',
            name='kategori',
            field=models.CharField(choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('insaat', 'İnşaat'), ('gida', 'Gıda'), ('ulasim', 'Ulaşım')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='sehir',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], max_length=20, verbose_name='Şehir'),
        ),
    ]
