# Generated by Django 4.2.4 on 2023-10-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0007_alter_sinopluyuz_kategori_alter_sinopluyuz_sehir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinopluyuz',
            name='is_active',
        ),
    ]
