# Generated by Django 4.2.4 on 2023-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0009_sinopluyuz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinopluyuz',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='kategori',
            field=models.CharField(choices=[('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('insaat', 'İnşaat'), ('gida', 'Gıda'), ('ulasim', 'Ulaşım'), ('diger', 'Diğer')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sinopluyuz',
            name='number',
            field=models.IntegerField(),
        ),
    ]
