# Generated by Django 4.2.4 on 2023-12-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0010_alter_sinopluyuz_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinopluyuz',
            name='sehir',
            field=models.CharField(choices=[('istanbul', 'İstanbul'), ('sinop', 'Sinop'), ('ankara', 'Ankara')], max_length=20, verbose_name='Şehirim'),
        ),
    ]
