# Generated by Django 4.2.4 on 2024-02-26 13:34

from django.db import migrations, models
import sinoplu.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoplu', '0011_alter_sinopluyuz_sehir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinopluyuz',
            name='image1',
            field=models.ImageField(upload_to=sinoplu.models.user_directory_path),
        ),
    ]
